### ISSUE TITLE
Test fails in production build

### ISSUE THREAD

**Issue by mvanbrab** [SolidLabResearch/generic-data-viewer-react-admin#159]
This test: <https://github.com/SolidLabResearch/generic-data-viewer-react-admin/blob/1ff848ed142766c526cb9dd34e12d45bd0925173/aux/cypress/e2e/custom-query-editor.cy.js#L141> fails with this output:

```
index-CNa2j_hy.js:95665 Error: The following error originated from your application code, not from Cypress.

  > ResizeObserver loop completed with undelivered notifications.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
  at <unknown> (http://localhost:5173/#/1724155056437:0:0)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:5173/__cypress/runner/cypress_runner.js:3486:19)
    at Promise._then (http://localhost:5173/__cypress/runner/cypress_runner.js:1239:17)
    at Promise._passThrough (http://localhost:5173/__cypress/runner/cypress_runner.js:4110:17)
    at Promise.lastly.Promise.finally (http://localhost:5173/__cypress/runner/cypress_runner.js:4119:17)
    at Object.onRunnableRun (http://localhost:5173/__cypress/runner/cypress_runner.js:163186:53)
    at $Cypress.action (http://localhost:5173/__cypress/runner/cypress_runner.js:41456:28)
    at Runnable.run (http://localhost:5173/__cypress/runner/cypress_runner.js:145774:13)
    at Runner.runTest (http://localhost:5173/__cypress/runner/cypress_runner.js:155716:10)
    at http://localhost:5173/__cypress/runner/cypress_runner.js:155842:12
    at next (http://localhost:5173/__cypress/runner/cypress_runner.js:155625:14)
    at http://localhost:5173/__cypress/runner/cypress_runner.js:155635:7
    at next (http://localhost:5173/__cypress/runner/cypress_runner.js:155537:14)
    at http://localhost:5173/__cypress/runner/cypress_runner.js:155603:5
    at timeslice (http://localhost:5173/__cypress/runner/cypress_runner.js:146114:27)
```

Seen in commit 1ff848ed142766c526cb9dd34e12d45bd0925173 on the main branch.

Was OK in previous commit b4d10f914d30d8e46b345b996964ffe5397588d9 on the main branch.

**Comment by mvanbrab** [comment]
This error is a harmless GUI thing.

It suddenly appears with versions bumps:
"@mui/icons-material": from "5.14.3" to "5.16.7",
"@mui/material": from "5.14.4" to "5.16.7".

It can be tolerated easily with `Cypress.on('uncaught:exception', ...)`
